services:
  kapital_api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - SERVICE_PORT=${SERVICE_PORT:-8000}
    container_name: kapital-api
    env_file:
      - .env
    environment:
      - SERVICE_PORT=${SERVICE_PORT:-8000}
    ports:
      - "${FASTAPI_EXTERNAL_PORT}:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVICE_PORT}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
